name: Publish to Docker Hub
on:
  push:
    branches:
      - main
jobs:
 deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip deploy]')"
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --unshallow
    - name: Dokku Deploy action
      uses: idoberko2/dokku-deploy-github-action@dd8a6aa3f08c890a24466a4dcd98165878fe3efb
      with:
        ssh-private-key: ${{ secrets.SSH_KEYS }}
        dokku-host: ${{ secrets.HOST }}
        app-name: ${{ secrets.APP }}
        remote-branch: main
